spring:
  datasource:
    url: jdbc:h2:mem:budget
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true