### 계정 생성
POST {{host}}/api/v1/accounts/join
Content-Type: application/json

{
  "id": "{{accountId}}",
  "password": "{{password}}",
  "nickname": "hyungyu"
}

### 계정 인증
POST {{host}}/api/v1/accounts/login
Content-Type: application/json

{
  "id": "{{accountId}}",
  "password": "{{password}}"
}

> {%
  client.global.set("accessToken", response.body.result.accessToken);
%}

### ADMIN 계정 인증
POST {{host}}/api/v1/accounts/login
Content-Type: application/json

{
  "id": "{{adminId}}",
  "password": "{{adminPassword}}"
}

> {%
  client.global.set("accessToken", response.body.result.accessToken);
%}

### 내 정보 조회
GET {{host}}/api/v1/accounts/me
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 존재하지 않는 API 호출
GET {{host}}/api/v1/accounts/mock
Content-Type: application/json
Authorization: Bearer {{accessToken}}