### 예산 생성
POST {{host}}/api/v1/budgets
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "createBudgets": [
    {
      "categoryId": 1,
      "amount": 100000
    },
    {
      "categoryId": 2,
      "amount": 200000
    },
    {
      "categoryId": 3,
      "amount": 300000
    },
    {
      "categoryId": 4,
      "amount": 400000
    },
    {
      "categoryId": 5,
      "amount": 200000
    },
    {
      "categoryId": 6,
      "amount": 300000
    },
    {
      "categoryId": 7,
      "amount": 300000
    },
    {
      "categoryId": 8,
      "amount": 100000
    }
  ]
}

### 내 예산 조회
GET {{host}}/api/v1/budgets/me
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 예산 수정
PUT {{host}}/api/v1/budgets/{{budgetId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "amount": 2000
}


### 예산 추천
POST {{host}}/api/v1/budgets/recommend
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "totalAmount": 200000
}